version: "3.8"
services:
  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - 80:80
      - 443:443
      - 81:81
    links:
      - phpfpm
      - mailhog
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./nginx/sites:/etc/nginx/sites-available
      - ./nginx/ssl:/etc/nginx/ssl
    volumes_from:
      - project
    extra_hosts:
      - snd.test:host-gateway
      - api.snd.test:host-gateway
      - kfui.test:host-gateway
      - snd.com:host-gateway
      - api.snd.com:host-gateway
      - assets.snd.com:host-gateway
      - ws.local.klikfx.com:host-gateway
    #expose:
    #  - 8045
  phpfpm:
    build: ./php/
    container_name: php82
    ports:
      - 9000:9000
      - 9045:9045      
    links:
      - mysql8
      - mailhog
    volumes:
      - ./php/phpfpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs/php:/var/log/php
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    volumes_from:
      - project
    extra_hosts:
      - project.docker.local:192.168.0.100
      - wordpress.loc:host-gateway
      - wp.local.klikfx.com:host-gateway
      - local.klikfx.com:host-gateway
      - host.docker.internal:host-gateway
      - snd.test:host-gateway
      - api.snd.test:host-gateway      
      - snd.com:host-gateway
      - assets.snd.com:host-gateway
      - api.snd.com:host-gateway 
      - kfui.test:host-gateway
      - ws.local.klikfx.com:host-gateway
    expose:
      - 9045
  node:
    image: node:20.8
    container_name: node
    volumes_from:
      - project
    #command: "tail -f /dev/null"  
    command: "npm run dev --prefix /var/www/html/snd/front"
    extra_hosts:
      - snd.test:host-gateway
      - api.snd.test:host-gateway
      - snd.com:host-gateway
      - assets.snd.com:host-gateway
      - api.snd.com:host-gateway   
      - ws.local.klikfx.com:host-gateway

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./redis:/data

  ngrok:
      image: ngrok/ngrok:latest
      container_name: ngrok
      restart: unless-stopped
      command:
        - "start"
        - "--all"
        - "--config"
        - "/etc/ngrok.yml"
      volumes:
        - /home/djuki/.config/ngrok/ngrok.yml:/etc/ngrok.yml
      ports:
        - 4040:4040

  project:
    image: alpine:latest
    container_name: project
    volumes:
      - ../..:/var/www/html
    command: "tail -f /dev/null"

  mysql:
    image: mysql:5.7
    container_name: mysql57
    ports:
      - 3306:3306
    volumes:
      - ./databases:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: surveyfunnel
      MYSQL_USER: default
      MYSQL_PASSWORD: secret

  mysql8:
    image: mysql:8.0.33
    container_name: mysql8
    ports:
      - 3306:3306
    volumes:
      - ./databases8:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: surveyfunnel
      MYSQL_USER: default
      MYSQL_PASSWORD: secret      

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8084:80
    links:
      - phpfpm
      - mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret_password
      PMA_HOST: mysql
      PMA_ARBITRARY: 1

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
  swoole:
    image: phpswoole/swoole
    environment:
      DISABLE_DEFAULT_SERVER: 1
    ports:
      - 9501:9501      