version: "3.8"
services:
  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - 80:80
      - 443:443
      - 81:81
    links:
      - php74
      - mailhog
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./nginx/sites:/etc/nginx/sites-available
      - ./nginx/ssl:/etc/nginx/ssl
    volumes_from:
      - project

  php74:
    build: ./php74/
    container_name: php74
    ports:
      - 9000:9000
    links:
      - mysql
      - mailhog
    volumes:
      - ./php/phpfpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs/php:/var/log/php
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    volumes_from:
      - project
    extra_hosts:
      - project.docker.local:192.168.0.100

  node:
    image: node:8.12.0-stretch
    container_name: node
    volumes_from:
      - project
    command: "tail -f /dev/null"      

  project:
    image: alpine:latest
    container_name: project
    volumes:
      - ../..:/var/www/html
      - ./storage:/var/www/storage
    command: "tail -f /dev/null"

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./databases:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: surveyfunnel
      MYSQL_USER: default
      MYSQL_PASSWORD: secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8084:80
    links:
      - php74
      - mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret_password
      PMA_HOST: mysql
      PMA_ARBITRARY: 1

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./redis:/data      

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025